### ISSUE TITLE
Address Label

### ISSUE THREAD

**Issue by BlueeeStar** [0xB10C/ofac-sanctioned-digital-currency-addresses#16]
Hello, how can I extract who these addresses belong to from the XML file. Is it possible to extract the tags for these addresses?

**Comment by 0xB10C** [comment]
>  how can I extract who these addresses belong to from the XML file

I'm not familiar with the exact layout of the XML file. You probably have to take a look for yourself.

> Is it possible to extract the tags for these addresses?

Sure. But I do not know what tags you mean.

**Comment by BlueeeStar** [comment]
I want to know which cryptocurrency addresses belong to whom.

Thank you.
